title: Jake0oo0
email: jake0oo0dev@gmail.com
description: 'My personal website.'
baseurl: ""
url: "http://jake0oo0.me"
twitter_username: Jake0oo0
github_username: Jake0oo0

# Build settings
markdown: kramdown
